# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48fba506df2e7cdb795c1db5926d2f516ccb819433e7a3d3c0aa330917c74cb54ba8b231bf4435635a9ba1d663b7187ee4f842249fb23c5de98360b0aea02a4f

test:
  secret_key_base: 7b0954fba2e53a427b942401b48c54ee2d42a488e8a0bc2026389e725bb927e4b5bc5f6e5ae8af53f3a4289b6b464a8c4d2a3349b1b4a195b0bfaee5a1ecedbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
